### ISSUE TITLE
Select & Input Field Text - add new tokens for icon and align design and code

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#1014]
### Description / User story

After discussing #567 in todays design review we decided to move this issue to after release 1.0 and instead focus on aligning design and code for the icons in the select and the input field text components without introducing a new component.

The solution would therefor just use the existing icon component and apply color and size tokens which will be defined by design.

The whole topic will be revisited with #567 in the future (after release 1.0) to identify and research if we need a separate input icon component which might then probably replace the current solution.

This ticket also solves #487 so this ticket has been closed.

### Requirements / Prerequisites

- none

### Acceptance Criteria

Select:
- [x] Design: The icon in the select uses its own color and sizing tokens.
- [x] Code: The icon in the select uses the defined color and sizing tokens from design.
- [x] Design: In error state the error icon has been removed. The chevron icon is always visible.
- [x] Code: In error state the error icon has been removed. The chevron icon is always visible.
- [x] Design & Code: The icon should be overwriteable

Input Field Text:
- [x] Design: The error icon inside the input field has been removed
- [x] Code: The error icon inside the input field has been removed
- [x] Design: In error state the icon part uses the newly defined color and sizing tokens
- [x] Code: In error state the icon part uses the defined color and sizing tokens from design
- [x] Design & Code: The icon should be overwriteable

### Additional information
- ...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by larserbach** [comment]
With this task we also removed read only state from the select component in design (the readonly state was never implemented, and is also not a standard feature of the html select element)

**Comment by thrbnhrtmnn** [comment]
Hey @larserbach , so https://github.com/deven-org/boiler/issues/476 is not needed anymore and can be closed, right?

**Comment by larserbach** [comment]
Yes, it's done

**Comment by thrbnhrtmnn** [comment]
PR is not moved yet :D
