### ISSUE TITLE
Button Text & Input Field Text - remove hasIcon prop

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#1028]
### Description / User story

As decided today and discussed on Friday within https://github.com/deven-org/boiler/pull/1023 we decided to align the icon visibility toggle in all components to use a "undefined" option in the icon prop instead of introducing a "hasIcon" prop.

The reason is, that this is also a better developer experience when working with the components and this is more important than a good storybook experience.

This also results in needed changes for the Button Text and Input Field Text components, where the hasIcon prop now needs to be removed. Other props like icon and iconPosition now also will always be displayed in Storybook.

### Requirements / Prerequisites

- none

### Acceptance Criteria

- [x] The hasIcon prop has been removed from the Button Text component
- [x] The icon and iconPosition props are now always displayed in Storybook (not only if hasIcon = true)
- [x] The hasIcon prop has been removed from the Input Field Text component
- [x] The icon prop is now always displayed in Storybook (not only if hasIcon = true)

### Additional information

- ...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bar-tay** [comment]
@thrbnhrtmnn should the number-input also get rid of its hasUnit prop since it is similar to hasIcon?

**Comment by thrbnhrtmnn** [comment]
Hey @bar-tay , sorry for the late response. I think this change would make sense, yes. But this was not part of this ticket. Would you prefer to still implement it or to have a follow up task (which we probably would give a low prio and move to the backlog).

**Comment by thrbnhrtmnn** [comment]
Hey @bar-tay , I left a review in your PR. The ACs are technically fulfilled, but there are some issues with your implementation
