### ISSUE TITLE
Text Area - resize icon fixes

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#1112]
### Description / User story

The resize icon in the text area component should be identical in design and code.
This means the resize icon should not be displayed in readonly and disabled state.

### Requirements / Prerequisites

- none

### Acceptance Criteria

- [ ] Resize icon is not displayed in readonly state in code
- [x] Resize icon is not displayed in disabled state in code

### Additional information

- ...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bar-tay** [comment]
@thrbnhrtmnn Hey,
It seems like the Resize Handler-Icon is not generated in the BLR-Icons. I guess we need to add that to the icon list from the design if it should be dynamically changeable.

**Comment by thrbnhrtmnn** [comment]
> @thrbnhrtmnn Hey, It seems like the Resize Handler-Icon is not generated in the BLR-Icons. I guess we need to add that to the icon list from the design if it should be dynamically changeable.

Hey @bar-tay , we have a task for this: https://github.com/deven-org/boiler/issues/1143, but it is not planned soon. Does this issue require this to be done or was this just a remark from your side?

**Comment by thrbnhrtmnn** [comment]
Okay, that is fine. This issue is only concerned with the states and not with the icon @bar-tay
