### ISSUE TITLE
[Bug]: For the Radios the pressed state is not aligned with the design

### ISSUE THREAD

**Issue by angsherpa456** [deven-org/boiler#1138]
### What is affected?

Component

### Description

For the Radio component, the pressed state is incorrectly implemented when you click on the radio control itself, but it works correctly when you click on the label.
Link for the design: https://www.figma.com/design/C4vgEKz8mKyulJ4gm3Qdql/%F0%9F%AB%A7-%5BBLR%5D-B01LER---UI-Kit?m=auto&node-id=11421-8049

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thrbnhrtmnn** [comment]
This ticket is the same as https://github.com/deven-org/boiler/issues/1141. As #1141 is described more detailed this task will be closed.
