### ISSUE TITLE
Define Browser Matrix

### ISSUE THREAD

**Issue by larsts2** [deven-org/boiler#3]
#### Description / User Story

We need to define a browser matrix, so it is clear what browsers B01LER will support and also with which Browsers we need to test all the components.

----
#### Acceptance Criteria
- [x] A browser matrix has been defined (Julian proposed to just cover the last 2 releases of the ["evergreens"](https://alvarotrigo.com/blog/evergreen-browser/))
- [x] Document the browser matrix in a support.md file in the repository (in the docs folder)

----
#### Background information
- Future task: Add the browser matrix to a page in storybook
- Lit update would have effect on browser matrix
- This only to have the matrix right now, changes will always happen in the future, we do not need to think too much about it.

**Comment by thrbnhrtmnn** [comment]
Already added a first version of this to the https://github.com/deven-org/B01LER-Kitchen/blob/develop/doc/SUPPORT.md file
