### ISSUE TITLE
Select - investigate if the icon should be optional

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#488]
#### Description / User Story

Currently the icon (chevron-down) is only shown if we want it. With this task we want to investigate and decide, if we should change this so that there is no option anymore and the component always handles this on their own.

----
#### Acceptance Criteria
- [x] It was researched and decided, if the option to show/hide the icon is still needed, if not, the option has been removed (task needs to change to type design & development then, so it also appears on dev board)
- [x] It was also researched and decided, if the icon should be changeable or if it should always be the chevron-down and the component was changed accordingly
- [x] It was researched and decided, if the error-icon should overlay the default icon or if this should be solved differently.

Sliced out to #1014 
- In case of decision to remove option: [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao) has been updated / comments have been resolved and props changed from red to black font color
- Component documentation in Storybook has been updated
- In case props were changed: [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao) has been updated / comments have been resolved and props changed from red to black font color > @thrbnhrtmnn or @angelicahoyss can support here

----
#### Background information
- ...

**Comment by larserbach** [comment]
After benchmarking selects I'd propose the following:
- The icon is mandatory
- A default icon (chevron-down) and icon size are defined
- The icon can be overridden, as seen here [chakra ui](https://chakra-ui.com/docs/components/select) or [Atlasian](https://atlassian.design/components/select/examples)
- In error state, the icon must not be exchanged with an error icon. (This topic is closely related to/blocked by #567 )

**Comment by thrbnhrtmnn** [comment]
Hey @larserbach , we can close this right? As discussed today, the update to the select will also be done as part of #1014, so there is nothing left to do here and this ticket only was about making the decision.
