### ISSUE TITLE
Checkbox - add required prop

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#673]
#### Description / User Story

The checkbox should also have a required prop.
The indeterminatedIcon prop should be renamed to indeterminateIcon.

----
#### Acceptance Criteria
- [x] The checkbox has a required prop, that functions exactly like in other form components
- [x] The section "Required" has been added under "Validation", incl. an example of a checkbox with required=true. Use the same text as defined in the [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao)
- [x] [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao) has been updated / comments have been resolved and props changed from red to black font color > @thrbnhrtmnn or @angelicahoyss can support here

----
#### Background information
- ...

**Comment by angelicahoyss** [comment]
Closing as duplicate, all of these tasks are included in #800

**Comment by thrbnhrtmnn** [comment]
Reopened this issue. The fix to add required prop should be part of this issue and the renaming will be moved to the prop alignment ticket
