### ISSUE TITLE
Documentation - README optimizations

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#709]
#### Description / User Story

After finalising #365 , we have talked with Julian and found some optimisations, which we should follow up on until the Beta release.

New points from Julian: 
> Ich habe mir die Boiler-Doku in Figma angeschaut: die ist recht ausführlich und erklärt auch einiges zu Setup und Usage. Vielleicht könnte man einfach noch mal darauf verweisen in der README.
> Und ansonsten habe ich nur noch als Punkt, dass sie erwähnen könnten, dass yarn start ein lokales storybook startet, aber das ist nur eine Kleinigkeit.

Translation:
- We should add a link/info to the README, which forwards to the Documentation in Figma, as it is very detailed and explaines a few things about Setup and Usability.
- We should mention, that "yarn start" starts a local storybook, which is just a small thing.

Also a link to the documentation how to change icons and fonts is included in the README (can be done once #921 and #629 are done).

----
#### Acceptance Criteria
- [x] Add Figma and Token Studio in the Requirement Section and explain, what they are doing
- [ ] Finalise "How to start" section:
   - [ ] Setup: Add info how to change "blr" prefix to something client specific
   - [x] Setup: Add a paragraph explaining that the token changes will be done via Figma and Tokens Studio and link to the getting started documentation in Figma
   - [x] Remove Usage section
- [x] Finalise "How to test" section
- [x] Add section that includes documentation on "how to build", "how to deploy" ~~and "how to dev"~~
- [x] Explain that yarn start opens a local storybook
- [x] Add sections from the Figma Getting started about the Setup and the Usability also to the README (we already have a link to this, but are not explaining that it also includes relevant information for devs)

----
#### Background information
- Section about how to change icon or fonts will be added with #921 and #629

**Comment by davidken91** [comment]
I think we can modify the acceptance criteria for this. Documentation can probably be removed since it will be handled by https://github.com/deven-org/B01LER-Kitchen/issues/368

**Comment by thrbnhrtmnn** [comment]
I would say we should not have a full in-depth deployment documentation within the readme, but we should have a short summary.
