### ISSUE TITLE
ToggleSwitch - add hasLabel prop

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#745]
#### Description / User Story

When #517 was created, we thought to already have this functionality in code. Right now this is not the case, therefor this issue was created.

----
#### Acceptance Criteria
- [x] ToggleSwitch has a "hasLabel" prop
- [x] If hasLabel=true, the label prop is also displayed in Storybook in the props panel and can be adjusted
- [x] If hasLabel=false, the label prop is not displayed in Storybook and the component does not have a label. It looks as defined in design.

----
#### Background information
- ...

**Comment by bar-tay** [comment]
@thrbnhrtmnn I added this prop here #1022
