### ISSUE TITLE
Radio - fix checked and error states

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#765]
#### Description / User Story

_Describe the ticket here or formulate a user story as follows:_

This issue fixes current issues with checking the control of the radio. Currently this is not possible. Also it should not be possible in Readonly. Furthermore it should be possible in error state.

----
#### Acceptance Criteria
- [x] The radio can be checked by either setting checked to true or clicking the control
- [x] ~Prevent click in readOnly,; focusing the control is still possible, but will not check the control~
- [x] Allow active option in error state and use the correct tokens
- [x] The Hover state for selected/checked radio is also working as defined in design
- [x] ~The Pressed state for selected/checked radio is also working as defined in design~

----
#### Background information
- _Add relevant information here_
- ...

**Comment by seemann** [comment]
We should discuss if the readonly status makes sense. The readonly attribute is not standard by input radios.

<img width="646" alt="Bildschirmfoto 2024-01-18 um 14 42 18" src="https://github.com/deven-org/B01LER-Kitchen/assets/265428/98e2e8d4-c6ae-4760-badf-1040516af6b0">

**Comment by seemann** [comment]
The fix for the uncheckable radios and the styling issues is merged.
The topic regarding the read-only state should be fixed in another ticket.

**Comment by thrbnhrtmnn** [comment]
Hey @seemann , I agree to slice out the read-only topic into a new ticket. But I also found an issue with the current implementation. It seems to me that the pressed state is not implemented as defined in design. At least I could not make it work. Can you have a look at that again?

**Comment by seemann** [comment]
Hey @thrbnhrtmnn, is it not this one?

https://github.com/deven-org/B01LER-Kitchen/assets/265428/263a1012-4c77-4c9f-b9f2-6490437b3a5f

**Comment by thrbnhrtmnn** [comment]
Hey @seemann , oh yes this looks correct. I did not see that, because I only pressed the control element. This does not seem to have the correct effect. 

@larserbach , am I correctly assuming that the pressed (and all other states) should also be triggered when interacting with the control? Please verify this :-)

Another question I now have is, if the effects should also be triggered when hovering/clicking/pressing the gap in-between the control and the label. Currently this is not the case in code.

**Comment by thrbnhrtmnn** [comment]
Added design label and changed type to dev & design, as a decision from design is still open.

**Comment by thrbnhrtmnn** [comment]
Last AC has been moved to #1073.

This issue can be closed now.
