### ISSUE TITLE
Form Caption - icon in sm is not center aligned

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#798]
#### Description / User Story

The icon in the Form Caption SM seems to be a bit off in code when compared to design. It seems like the icon is not center aligned, but bottom right aligned in the wrapping 14x14 px container. The issue might also be there in other sizes, but not that recognizable.

----
#### Acceptance Criteria
- [ ] The icon placement within its container within the Form Caption has been investigated
- [ ] The icon has been adjusted so it is perfectly aligned with design
- [ ] Property name "ignoreSize" has been changed to "fillParent" for all components
- [ ] "fillParent" default should be true for icon component
- [ ] "sizeVariant" prop should only be displayed in prop panel of icon component in Storybook, if fillParent=false 

----
#### Background information
- _Add relevant information here_
- ...

**Comment by larserbach** [comment]
I took a look. (on Render with Firefox) The vertical alignment is correct in all size variants.
The technical solution differs from the design solution. There is no wrapper for the icon created, the padding is applied on the icon directly. Yet the visual result is the same as in design, therefor the ticket can be closed from my perspective.
