### ISSUE TITLE
Radio - Ensure Consistency between Storybook Documentation and Codebase Property Names

### ISSUE THREAD

**Issue by angelicahoyss** [deven-org/boiler#823]
#### Prerequisite

https://github.com/deven-org/B01LER-Kitchen/issues/824 is done and closed
https://github.com/deven-org/B01LER-Kitchen/issues/521 is done and closed

#### Description / User Story

**As a** developer on the team,
**I want** to ensure consistency between the property names defined in the Storybook documentation for Radio component
**So that** the Radio component codebase accurately reflects the documented property names.

This user story outlines the need to maintain consistency between the documentation and the codebase regarding component property names. Each component is checked to ensure the property names in the codebase match the corresponding names in the Storybook documentation. **If the discrepancies are found, they are listed in[ this table](https://ts.accenture.com/:x:/r/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc=%7Bb2cc9fb8-5c39-4049-9652-a4e6bbe09ef1%7D&action=editnew) on the page "Radio".** Column Current Code Property Name describes how is the property currently named in the code. Column Desired Code Property Name is how the property should be named. Properties marked green don't need adjustment.

----
#### Acceptance Criteria

- [x]  All Radio component's property names that differ from Storybook documentation property names (listed in the above mentioned table) should be updated
- [x] The updated property names should not introduce any unintended side effects or issues in the functionality of the components
- [x] "araiaLabel" should be renamed to ariaLabel in Storybook file (Documentation)
- [x] The library builds successfully, and there are no reported issues related to the property name updates 
- [ ] [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao) has been updated / comments have been resolved and props changed from red to black font color > @thrbnhrtmnn or @angelicahoyss can support here

**Comment by thrbnhrtmnn** [comment]
Hey @angelicahoyss , I think you copy pasted the description from the checkbox issue, right? Checkbox was mentioned a few times in the user story in the description. I changed it now to "Radio".

**Comment by angelicahoyss** [comment]
Sorry @thrbnhrtmnn I thought I replaced it! Thank you :)

**Comment by bar-tay** [comment]
@thrbnhrtmnn I don't think the value prop is needed since we already use the label prop to manipulate the text

**Comment by thrbnhrtmnn** [comment]
Hey @bar-tay , you can ignore the value prop for now, as it has its own ticket: https://github.com/deven-org/boiler/issues/824 .

We should discuss in a refinement session, if this change is really needed.

**Comment by thrbnhrtmnn** [comment]
@bar-tay , no, not yet. But should still be able to do this ticket, just ignore the value prop for now. Last time i checked the PR it already looked good, but I was waiting for a dev to also have a look and approve before I would look again and approve
