### ISSUE TITLE
Number Input - Ensure Consistency between Storybook Documentation and Codebase Property Names

### ISSUE THREAD

**Issue by angelicahoyss** [deven-org/boiler#831]
#### Prerequisite

Name property is added to the component https://github.com/deven-org/B01LER-Kitchen/issues/834

#### Description / User Story

**As a** developer on the team,
**I want** to ensure consistency between the property names defined in the Storybook documentation for Number Input component
**So that** the Number Input component codebase accurately reflects the documented property names.

This user story outlines the need to maintain consistency between the documentation and the codebase regarding component property names. Each component is checked to ensure the property names in the codebase match the corresponding names in the Storybook documentation. **If the discrepancies are found, they are listed in[ this table](https://ts.accenture.com/:x:/r/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc=%7Bb2cc9fb8-5c39-4049-9652-a4e6bbe09ef1%7D&action=editnew) on the page "Number Input".** Column Current Code Property Name describes how is the property currently named in the code. Column Desired Code Property Name is how the property should be named. Properties marked green don't need adjustment.

----
#### Acceptance Criteria

- [ ]  All Number Input component's property names that differ from Storybook documentation property names (listed in the above mentioned table) should be updated
- [ ] The updated property names should not introduce any unintended side effects or issues in the functionality of the components
- [ ] prependUnit should to be renamed in Storybook file (Documentation) to hasUnit, in addition to renaming the code property (this also includes changing this from a boolean to a radio with 3 options, changing the default to "none" and only displaying the unit prop in the prop panel if hasUnit is not "none")
- [ ] The properties in the props panel in Storybook are following the same order as in the Excel (i.e. the Accessibility section should come before the Technical Attributes section)
- [ ] The library builds successfully, and there are no reported issues related to the property name updates 
- [ ] [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao) has been updated / comments have been resolved and props changed from red to black font color > @thrbnhrtmnn or @angelicahoyss can support here

**Comment by JpunktWpunkt** [comment]
it would be nice to have this PR merged before we finished this [feat/481_number-input-events](https://github.com/deven-org/boiler/pull/937)
