### ISSUE TITLE
Radio, Radio Group, Checkbox, Toggle Switch - research if we should remove readonly state

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#832]
#### Description / User Story

With #765 a discussion was started to remove the readonly state from the radio, as it is not standard for a radio, according to:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly

Bildschirmfoto 2024-01-18 um 14 42 18

Within this issue we should decide how to proceed and either remove or fix the readonly state.

This decision should also look at similar components like Checkbox and Toggle Switch.

**UPDATE 19.04.** Remmy got some input  about whether the readonly state is allowed for these components from an a11y point of view. [Here](https://ts.accenture.com/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc={98a173b4-59fa-4788-8e52-1d29bc00e992}&action=edit&wd=target%28B01LER%20Meeting-Notes.one%7Ceb994392-972f-43d3-9237-926069ea0cc1%2F2024-04-19%20Chat%20with%20Remmy%20about%20readonly%20%7C9a28c70c-a567-49a2-8cda-4662c88a2980%2F%29&wdorigin=703) is a link to the input / chat.

----
#### Acceptance Criteria
- [x] It was decided by design, if the radio, radio group, checkbox and toggle switch still needs a readonly state or not.
- [x] If decision was to remove the readonly state for the radio, radio group, checkbox and toggle switch:
   - [x] Readonly state has been removed in design
   - [x] Readonly state has been removed in code
- [x] ~If decision was to keep the readonly state for the radio, radio group, checkbox and toggle switch:~
   - [x] ~In code, a click in readonly state is prevented for the radio, radio group, checkbox and toggle switch~
   - [x] ~In code, focusing the control of the radio, radio group, checkbox and toggle switch in readonly state is still possible, but will not check the control~
   - [x] ~In code, the readonly state is implemented accessible (use right roles and aria labels)~

----
#### Background information
- _Add relevant information here_
- ...

**Comment by larserbach** [comment]
Research Outcome:
- It is not common practice to provide readOnly for Radio, Checkbox, Toggle
- If I think about it, it actually wouldn't make sense. I understand readonly as a state which enables the user to select a value from a component, but blocks any further interaction. Now, what would a user gain from coping over "true"  or  "false"
- This being said, "disabled" is fully sufficient. 
- The label of the named components must be selectable, in order to allow the user to copy the string - this is currently true in our DS for toggle and checkbox, but not for radio. let's fix it.

**Comment by thrbnhrtmnn** [comment]
Thank you for the research @larserbach! If I understood you correctly we shoudl remove the readonly state then for Checkbox, Radio, Radio Group and Toggle Switch. 

I updated the ACs accordingly, this task would be done, once the readonly state have been removed from the mentioned components in design and in code.

Regarding your last point: In Chrome selecting the label of the radio as well as the radio group works in storybook, but on Firefox it did not work. I will create a separate bug ticket to fix this for Firefox. If there are other browsers where we have the issues please let me know.
