### ISSUE TITLE
Select - Ensure Consistency between Storybook Documentation and Codebase Property Names

### ISSUE THREAD

**Issue by angelicahoyss** [deven-org/boiler#872]
### Description / User story

As a developer on the team,
I want to ensure consistency between the property names defined in the Storybook documentation for Select component
So that the Select component codebase accurately reflects the documented property names.

This user story outlines the need to maintain consistency between the documentation and the codebase regarding component property names. Each component is checked to ensure the property names in the codebase match the corresponding names in the Storybook documentation. If the discrepancies are found, they are listed in[ this table](https://ts.accenture.com/:x:/r/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc=%7Bb2cc9fb8-5c39-4049-9652-a4e6bbe09ef1%7D&action=editnew) on the page "Select". Column Current Code Property Name describes how is the property currently named in the code. Column Desired Code Property Name is how the property should be named. Properties marked green don't need adjustment

### Acceptance Criteria

- [x]  All Select component's property names that differ from Storybook documentation property names (listed in the above mentioned table) should be updated
- [ ] The event properties in the prop panel are the same as in the component/the props excel, where they have been renamed in the past
- [x] The updated property names should not introduce any unintended side effects or issues in the functionality of the components
- [x] The library builds successfully, and there are no reported issues related to the property name updates 
- [ ] [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao) has been updated / comments have been resolved and props changed from red to black font color > @thrbnhrtmnn or @angelicahoyss can support here

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by thrbnhrtmnn** [comment]
Hey @bar-tay ,

I am afraid we have to reopen this issue as we have a few open topics, as the properties in the prop panel are not yet the same as in the props excel and in the components:
- the order of the props is not the same
- please remove the required prop from the props panel
- I think the children (options) prop should be removed in the props panel, as it should have been removed from the component via #739 
- The blrFocus and blrBlur event do not seem to function, when testing the select in the example application (not sure if this was the case before)

**Comment by bar-tay** [comment]
Ahh! I thought this is about the behaviour in storybook and not in the js-example. The code of the component which is represented in storybook is not connected to the component code in the js-example. The code of the events in all storybook files you mentioned is actually the same in the select storybook file. This problem with the events not firing is probably related to something in the general component file structure which we use in the js-example and not the prop alignment. Gonna luck further into this.

**Comment by thrbnhrtmnn** [comment]
In Storybook the events also work for Button Text and Input Field Text. If I open the Actions Bar, I see the following:
![Screenshot 2024-03-12 at 14 36 01](https://github.com/deven-org/boiler/assets/122102805/bfd73c08-378d-4e24-8ece-fc0e904a1be7)

**Comment by thrbnhrtmnn** [comment]
@bar-tay I am so sorry, I have to reopen this issue and we have to make another branch.

I told you the wrong prop to remove. We should remove "readonly" and not "required.

Also I found another minor thing. Please also hide "labelAppendix" prop in the prop panel, if hasLabel = false.

**Comment by bar-tay** [comment]
@thrbnhrtmnn done :)
