### ISSUE TITLE
Input Field Number - fix width of horizontal stepper variant

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#932]
### Description / User story

The width of the stepper buttons in the stepper variant "horizontal" of the Input Field Number is not aligned between design and code.

In design the each stepper button should be squared (i.e. 32x32 in SM), but in code the width is smaller than it should be and even changes when the width of the wrapping container of the Input Field Number changes.

The width in code should be aligned with the width in design.

### Requirements / Prerequisites

- none

### Acceptance Criteria

- [x] The width of the Stepper Buttons in the "horizontal" stepper variant of the Input Field Number is the same in code as in design (32 px in SM, 40 px in MD and 48 px in LG)

### Additional information

- ...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AnukratiMehta** [comment]
I'd like to give this a try @thrbnhrtmnn.

**Comment by thrbnhrtmnn** [comment]
Hey @AnukratiMehta , thanks for reaching out and for wanting to contribute to the project!

Unfortunately we are currently doing a massive update to our CSS, so I would highly recommend to wait a bit before starting this issue. We probably will finish it this week, maybe even today. I will let you know when this can be started :-)

**Comment by thrbnhrtmnn** [comment]
Hello @AnukratiMehta , it took a bit longer, but we just finished the CSS update. If you still want to give this a try, please go ahead :-)
