### ISSUE TITLE
Define events that need to be added to our components

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#972]
### Description / User story

To make our components more usable we need to extend the events that we currently have.

This issue is to figure out which events we want to add to which components, before adding them in follow-up issues.

Here is an overview of the currently planned events for our components (most recent version can be found [here](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=5ihXLE)):

Event | Components
-- | --
blrChange | SliderSingleValue, RadioGroup, ToggleSwitch, Radio, SliderTwoValues, TabBar
blrCheckedChange | Checkbox
blrNumberValueChange | NumberInput
blrSelectedValueChange | Select
blrTextValueChange | TextArea, TextInput
blrClick | TextButton, IconButton (use pointer events instead)
blrSelect | TextArea, TextInput, NumberInput
blrFocus | TextArea, TextInput, NumberInput, SliderSingleValue, TextButton, IconButton, Select, RadioGroup, Checkbox, ToggleSwitch, TabBar, Radio, SliderTwoValues
blrBlur | TextArea, TextInput, NumberInput, SliderSingleValue, TextButton, IconButton, Select, RadioGroup, Checkbox, ToggleSwitch, TabBar, Radio, SliderTwoValues
blrNumberStepperClick | SliderSingleValue, SliderTwoValues, NumberInput

### Requirements / Prerequisites

- [ ] none

### Acceptance Criteria

- [x] We have defined which events we should add to which components
- [x] We will use pointer events to handle mouse and touch unified. 
- [x] Follow-Up issues to implement these events have been created and refined

### Additional information

- [Pointer Events](https://javascript.info/pointer-events)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by angsherpa456** [comment]
The following events can be added to the respective components: 

1. InputField: [onValid, onInvalid] for email/password type.
2. Select: ['keyup/keydown']
3. Tabs: ['keyup/keydown', 'onChange'], // Currently only the **space** key press implemented, Enter key press should be implemented as well.
4. ButtonText: ['keyup/keydown'], // Currently only the **space** key press implemented, Enter key press should be implemented as well.
5. TextArea: ['onPaste']
6. ToggleSwitch: ['keyup/keydown'], // right now nothing happens

Note: Pointer events seems to be over-kill for now as we have the basic components for now and click event handler is suffice. It might be more relevant when implementing something complex like drag and drop feature.

**Comment by thrbnhrtmnn** [comment]
After discussing this today with @faselbaum , we decided on the following:
- New ticket to discuss general event approach:
   -  Do we really need custom events, where the event payload is the same as the native payload, if so, should we reimplement all standard events as custom events to give developers flexibility when using our components? > Define general rules for events.
   - How can users attach eventListeners to specific child elements inside the Shadow DOM in case we forgot to add some needed events?

After the general approach is defined, we can also define which of the suggested events we will add.
