### ISSUE TITLE
Check if all components have unit tests

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#985]
### Description / User story

We should check if all components have unit tests. In follow-up tasks we will add missing unit tests.

### Requirements / Prerequisites

- none

### Acceptance Criteria

- [x] All components have been checked, if they have unit tests or if they are missing important unit tests
- [x] The status of our unit test coverage has been documented in this issue
- [x] ~Follow-up tasks to implement missing unit tests that we need for 1.0 have been created~ > not needed

### Additional information

- ...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by veilvokay** [comment]
| Component (subcomponent)       | Tests coverage     |
|--------------------------------|--------------------|
| button-group                   | :white_check_mark: |
| checkbox                       | :white_check_mark: |
| counter                        | :white_check_mark: |
| divider                        | :white_check_mark: |
| form-caption                   | :white_check_mark: |
| form-caption-group             | :white_check_mark: |
| form-label (form-label)        | :white_check_mark: |
| form-label (form-label-inline) | :x:                   |
| icon                           | :white_check_mark: |
| icon-button                    | :white_check_mark: |
| icon-link                      | :white_check_mark: |
| loader                         | :white_check_mark: |
| number-input                   | :white_check_mark: |
| radio                          | :white_check_mark: |
| radio-group                                     | :white_check_mark: |
| select                                          | :white_check_mark: |
| slider-single-value (range-slider)              | :white_check_mark: |
| slider-single-value (range-legend-slider)       | :white_check_mark: |
| slider-two-values (range-min-max-slider)        | :white_check_mark: |
| slider-two-values (range-legend-min-max-slider) | :x:                |
| tab-bar                                         | :white_check_mark: |
| text-button                                     | :white_check_mark: |
| text-input                                      | :white_check_mark: |
| textarea                                        | :white_check_mark: |
| toggle-switch                                   | :white_check_mark: |
| tooltip - will be reworked in [860](https://github.com/deven-org/boiler/issues/860)              | :white_check_mark: |
| tooltip-bubble                                  | :white_check_mark: |

**Comment by veilvokay** [comment]
Follow up ticket: https://github.com/deven-org/boiler/issues/989

**Comment by thrbnhrtmnn** [comment]
Thank you @veilvokay , I think this ticket is already done and can be closed. Or is there anything open on your side?

**Comment by veilvokay** [comment]
> Thank you @veilvokay , I think this ticket is already done and can be closed. Or is there anything open on your side?

form-label (form-label-inline) --> not a real component and can be treated-merged into form-label (form-label).
slider-two-values (range-legend-min-max-slider) --> tests added and merged under this ticket #993 

Can be closed.
